language: go
sudo: false
env:
  - GO111MODULE=on
go:
  - 1.12.x
git:
  depth: 1
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9218717a-ddf3-476e-8929-a6471991c4fe